// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: protos/service/job_posting_service.grpc.proto

package service

import (
	domain "github.com/wanpng/job-posting-grpc/grpc/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobSeekerJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobseekerId string `protobuf:"bytes,1,opt,name=jobseeker_id,json=jobseekerId,proto3" json:"jobseeker_id,omitempty"`
}

func (x *GetJobSeekerJobsRequest) Reset() {
	*x = GetJobSeekerJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsRequest) ProtoMessage() {}

func (x *GetJobSeekerJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsRequest.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobSeekerJobsRequest) GetJobseekerId() string {
	if x != nil {
		return x.JobseekerId
	}
	return ""
}

type GetJobSeekerJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HiddenJobs []*Job `protobuf:"bytes,1,rep,name=hiddenJobs,proto3" json:"hiddenJobs,omitempty"`
	SavedJobs  []*Job `protobuf:"bytes,2,rep,name=savedJobs,proto3" json:"savedJobs,omitempty"`
}

func (x *GetJobSeekerJobsResponse) Reset() {
	*x = GetJobSeekerJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsResponse) ProtoMessage() {}

func (x *GetJobSeekerJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsResponse.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobSeekerJobsResponse) GetHiddenJobs() []*Job {
	if x != nil {
		return x.HiddenJobs
	}
	return nil
}

func (x *GetJobSeekerJobsResponse) GetSavedJobs() []*Job {
	if x != nil {
		return x.SavedJobs
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetApplicationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobseekerId string `protobuf:"bytes,2,opt,name=jobseeker_id,json=jobseekerId,proto3" json:"jobseeker_id,omitempty"`
}

func (x *GetApplicationStatusRequest) Reset() {
	*x = GetApplicationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusRequest) ProtoMessage() {}

func (x *GetApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetApplicationStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetApplicationStatusRequest) GetJobseekerId() string {
	if x != nil {
		return x.JobseekerId
	}
	return ""
}

type GetApplicationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationStatuId int32  `protobuf:"varint,1,opt,name=application_statu_id,json=applicationStatuId,proto3" json:"application_statu_id,omitempty"`
	ApplicationStatus  string `protobuf:"bytes,2,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"`
}

func (x *GetApplicationStatusResponse) Reset() {
	*x = GetApplicationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusResponse) ProtoMessage() {}

func (x *GetApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationStatusResponse) GetApplicationStatuId() int32 {
	if x != nil {
		return x.ApplicationStatuId
	}
	return 0
}

func (x *GetApplicationStatusResponse) GetApplicationStatus() string {
	if x != nil {
		return x.ApplicationStatus
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *domain.JobGrpc `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobResponse) GetJob() *domain.JobGrpc {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetJobUserRequest) Reset() {
	*x = GetJobUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobUserRequest) ProtoMessage() {}

func (x *GetJobUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobUserRequest.ProtoReflect.Descriptor instead.
func (*GetJobUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetJobUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *domain.UserGrpc `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetJobUserResponse) Reset() {
	*x = GetJobUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobUserResponse) ProtoMessage() {}

func (x *GetJobUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobUserResponse.ProtoReflect.Descriptor instead.
func (*GetJobUserResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobUserResponse) GetUser() *domain.UserGrpc {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateJobUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *domain.UserGrpc `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateJobUserRequest) Reset() {
	*x = UpdateJobUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobUserRequest) ProtoMessage() {}

func (x *UpdateJobUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateJobUserRequest) GetUser() *domain.UserGrpc {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateJobUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UpdateJobUserResponse) Reset() {
	*x = UpdateJobUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobUserResponse) ProtoMessage() {}

func (x *UpdateJobUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobUserResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateJobUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SearchJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerIds []string `protobuf:"bytes,1,rep,name=employer_ids,json=employerIds,proto3" json:"employer_ids,omitempty"`
	Keyword     string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *SearchJobRequest) Reset() {
	*x = SearchJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobRequest) ProtoMessage() {}

func (x *SearchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobRequest.ProtoReflect.Descriptor instead.
func (*SearchJobRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *SearchJobRequest) GetEmployerIds() []string {
	if x != nil {
		return x.EmployerIds
	}
	return nil
}

func (x *SearchJobRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobIds []string `protobuf:"bytes,1,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
}

func (x *SearchJobResponse) Reset() {
	*x = SearchJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobResponse) ProtoMessage() {}

func (x *SearchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobResponse.ProtoReflect.Descriptor instead.
func (*SearchJobResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *SearchJobResponse) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type GetJobsByEmployerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerId  string `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Photo       string `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	IsLanco     bool   `protobuf:"varint,4,opt,name=is_lanco,json=isLanco,proto3" json:"is_lanco,omitempty"`
}

func (x *GetJobsByEmployerRequest) Reset() {
	*x = GetJobsByEmployerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobsByEmployerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsByEmployerRequest) ProtoMessage() {}

func (x *GetJobsByEmployerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsByEmployerRequest.ProtoReflect.Descriptor instead.
func (*GetJobsByEmployerRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobsByEmployerRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *GetJobsByEmployerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetJobsByEmployerRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *GetJobsByEmployerRequest) GetIsLanco() bool {
	if x != nil {
		return x.IsLanco
	}
	return false
}

type GetJobsByEmployerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployerId  string `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Photo       string `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Jobs        []*Job `protobuf:"bytes,4,rep,name=jobs,proto3" json:"jobs,omitempty"`
	IsLanco     bool   `protobuf:"varint,5,opt,name=is_lanco,json=isLanco,proto3" json:"is_lanco,omitempty"`
}

func (x *GetJobsByEmployerResponse) Reset() {
	*x = GetJobsByEmployerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobsByEmployerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsByEmployerResponse) ProtoMessage() {}

func (x *GetJobsByEmployerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsByEmployerResponse.ProtoReflect.Descriptor instead.
func (*GetJobsByEmployerResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobsByEmployerResponse) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *GetJobsByEmployerResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetJobsByEmployerResponse) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *GetJobsByEmployerResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetJobsByEmployerResponse) GetIsLanco() bool {
	if x != nil {
		return x.IsLanco
	}
	return false
}

var File_protos_service_job_posting_service_grpc_proto protoreflect.FileDescriptor

var file_protos_service_job_posting_service_grpc_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4a, 0x6f, 0x62, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x0a, 0x68, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x64, 0x4a,
	0x6f, 0x62, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x09,
	0x73, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x1c, 0x0a, 0x03, 0x4a, 0x6f, 0x62,
	0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x7f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x14, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x47, 0x72, 0x70, 0x63,
	0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x70, 0x63, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a,
	0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2c,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x73, 0x22, 0x8f, 0x01, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x42, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x61, 0x6e, 0x63, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x61, 0x6e, 0x63, 0x6f, 0x22, 0xb9,
	0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x42, 0x79, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x61, 0x6e, 0x63, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x61, 0x6e, 0x63, 0x6f, 0x32, 0xa7, 0x05, 0x0a, 0x11, 0x4a,
	0x6f, 0x62, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x7b, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x41, 0x6e, 0x64, 0x53, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f,
	0x62, 0x73, 0x49, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x1a, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x53, 0x0a,
	0x0a, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x50, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x12,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x42,
	0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x73, 0x42, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x42, 0x79, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a,
	0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x70, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x6e, 0x70,
	0x6e, 0x67, 0x2e, 0x6a, 0x6f, 0x62, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x17, 0x4a, 0x6f, 0x62, 0x50,
	0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce sync.Once
	file_protos_service_job_posting_service_grpc_proto_rawDescData = file_protos_service_job_posting_service_grpc_proto_rawDesc
)

func file_protos_service_job_posting_service_grpc_proto_rawDescGZIP() []byte {
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce.Do(func() {
		file_protos_service_job_posting_service_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_service_job_posting_service_grpc_proto_rawDescData)
	})
	return file_protos_service_job_posting_service_grpc_proto_rawDescData
}

var file_protos_service_job_posting_service_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_service_job_posting_service_grpc_proto_goTypes = []interface{}{
	(*GetJobSeekerJobsRequest)(nil),      // 0: protos.service.GetJobSeekerJobsRequest
	(*GetJobSeekerJobsResponse)(nil),     // 1: protos.service.GetJobSeekerJobsResponse
	(*Job)(nil),                          // 2: protos.service.Job
	(*GetApplicationStatusRequest)(nil),  // 3: protos.service.GetApplicationStatusRequest
	(*GetApplicationStatusResponse)(nil), // 4: protos.service.GetApplicationStatusResponse
	(*GetJobRequest)(nil),                // 5: protos.service.GetJobRequest
	(*GetJobResponse)(nil),               // 6: protos.service.GetJobResponse
	(*GetJobUserRequest)(nil),            // 7: protos.service.GetJobUserRequest
	(*GetJobUserResponse)(nil),           // 8: protos.service.GetJobUserResponse
	(*UpdateJobUserRequest)(nil),         // 9: protos.service.UpdateJobUserRequest
	(*UpdateJobUserResponse)(nil),        // 10: protos.service.UpdateJobUserResponse
	(*SearchJobRequest)(nil),             // 11: protos.service.SearchJobRequest
	(*SearchJobResponse)(nil),            // 12: protos.service.SearchJobResponse
	(*GetJobsByEmployerRequest)(nil),     // 13: protos.service.GetJobsByEmployerRequest
	(*GetJobsByEmployerResponse)(nil),    // 14: protos.service.GetJobsByEmployerResponse
	(*domain.JobGrpc)(nil),               // 15: protos.domain.JobGrpc
	(*domain.UserGrpc)(nil),              // 16: protos.domain.UserGrpc
	(*domain.CandidateSkills)(nil),       // 17: protos.domain.CandidateSkills
}
var file_protos_service_job_posting_service_grpc_proto_depIdxs = []int32{
	2,  // 0: protos.service.GetJobSeekerJobsResponse.hiddenJobs:type_name -> protos.service.Job
	2,  // 1: protos.service.GetJobSeekerJobsResponse.savedJobs:type_name -> protos.service.Job
	15, // 2: protos.service.GetJobResponse.job:type_name -> protos.domain.JobGrpc
	16, // 3: protos.service.GetJobUserResponse.user:type_name -> protos.domain.UserGrpc
	16, // 4: protos.service.UpdateJobUserRequest.user:type_name -> protos.domain.UserGrpc
	2,  // 5: protos.service.GetJobsByEmployerResponse.jobs:type_name -> protos.service.Job
	0,  // 6: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:input_type -> protos.service.GetJobSeekerJobsRequest
	5,  // 7: protos.service.JobPostingService.GetJob:input_type -> protos.service.GetJobRequest
	17, // 8: protos.service.JobPostingService.SaveJobSeekerSkills:input_type -> protos.domain.CandidateSkills
	7,  // 9: protos.service.JobPostingService.getJobUser:input_type -> protos.service.GetJobUserRequest
	11, // 10: protos.service.JobPostingService.SearchJob:input_type -> protos.service.SearchJobRequest
	13, // 11: protos.service.JobPostingService.GetJobsByEmployer:input_type -> protos.service.GetJobsByEmployerRequest
	9,  // 12: protos.service.JobPostingService.UpdateJobUserEmployer:input_type -> protos.service.UpdateJobUserRequest
	1,  // 13: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:output_type -> protos.service.GetJobSeekerJobsResponse
	6,  // 14: protos.service.JobPostingService.GetJob:output_type -> protos.service.GetJobResponse
	17, // 15: protos.service.JobPostingService.SaveJobSeekerSkills:output_type -> protos.domain.CandidateSkills
	8,  // 16: protos.service.JobPostingService.getJobUser:output_type -> protos.service.GetJobUserResponse
	12, // 17: protos.service.JobPostingService.SearchJob:output_type -> protos.service.SearchJobResponse
	14, // 18: protos.service.JobPostingService.GetJobsByEmployer:output_type -> protos.service.GetJobsByEmployerResponse
	10, // 19: protos.service.JobPostingService.UpdateJobUserEmployer:output_type -> protos.service.UpdateJobUserResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protos_service_job_posting_service_grpc_proto_init() }
func file_protos_service_job_posting_service_grpc_proto_init() {
	if File_protos_service_job_posting_service_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_service_job_posting_service_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateJobUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateJobUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobsByEmployerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobsByEmployerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_service_job_posting_service_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_job_posting_service_grpc_proto_goTypes,
		DependencyIndexes: file_protos_service_job_posting_service_grpc_proto_depIdxs,
		MessageInfos:      file_protos_service_job_posting_service_grpc_proto_msgTypes,
	}.Build()
	File_protos_service_job_posting_service_grpc_proto = out.File
	file_protos_service_job_posting_service_grpc_proto_rawDesc = nil
	file_protos_service_job_posting_service_grpc_proto_goTypes = nil
	file_protos_service_job_posting_service_grpc_proto_depIdxs = nil
}
