// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: protos/service/job_posting_service.grpc.proto

package service

import (
	domain "github.com/wanpng/job-posting-grpc/grpc/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobSeekerJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobseekerId string `protobuf:"bytes,1,opt,name=jobseeker_id,json=jobseekerId,proto3" json:"jobseeker_id,omitempty"`
}

func (x *GetJobSeekerJobsRequest) Reset() {
	*x = GetJobSeekerJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsRequest) ProtoMessage() {}

func (x *GetJobSeekerJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsRequest.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobSeekerJobsRequest) GetJobseekerId() string {
	if x != nil {
		return x.JobseekerId
	}
	return ""
}

type GetJobSeekerJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HiddenJobs []*Job `protobuf:"bytes,1,rep,name=hiddenJobs,proto3" json:"hiddenJobs,omitempty"`
	SavedJobs  []*Job `protobuf:"bytes,2,rep,name=savedJobs,proto3" json:"savedJobs,omitempty"`
}

func (x *GetJobSeekerJobsResponse) Reset() {
	*x = GetJobSeekerJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsResponse) ProtoMessage() {}

func (x *GetJobSeekerJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsResponse.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobSeekerJobsResponse) GetHiddenJobs() []*Job {
	if x != nil {
		return x.HiddenJobs
	}
	return nil
}

func (x *GetJobSeekerJobsResponse) GetSavedJobs() []*Job {
	if x != nil {
		return x.SavedJobs
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetApplicationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobseekerId string `protobuf:"bytes,2,opt,name=jobseeker_id,json=jobseekerId,proto3" json:"jobseeker_id,omitempty"`
}

func (x *GetApplicationStatusRequest) Reset() {
	*x = GetApplicationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusRequest) ProtoMessage() {}

func (x *GetApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetApplicationStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetApplicationStatusRequest) GetJobseekerId() string {
	if x != nil {
		return x.JobseekerId
	}
	return ""
}

type GetApplicationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationStatuId int32  `protobuf:"varint,1,opt,name=application_statu_id,json=applicationStatuId,proto3" json:"application_statu_id,omitempty"`
	ApplicationStatus  string `protobuf:"bytes,2,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"`
}

func (x *GetApplicationStatusResponse) Reset() {
	*x = GetApplicationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusResponse) ProtoMessage() {}

func (x *GetApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationStatusResponse) GetApplicationStatuId() int32 {
	if x != nil {
		return x.ApplicationStatuId
	}
	return 0
}

func (x *GetApplicationStatusResponse) GetApplicationStatus() string {
	if x != nil {
		return x.ApplicationStatus
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *domain.JobGrpc `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobResponse) GetJob() *domain.JobGrpc {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_protos_service_job_posting_service_grpc_proto protoreflect.FileDescriptor

var file_protos_service_job_posting_service_grpc_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6a,
	0x6f, 0x62, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x62, 0x73,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f,
	0x62, 0x52, 0x0a, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x31, 0x0a,
	0x09, 0x73, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x09, 0x73, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73,
	0x22, 0x1c, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x73,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64,
	0x22, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4a, 0x6f, 0x62, 0x47, 0x72, 0x70, 0x63, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x32, 0xa1, 0x03, 0x0a,
	0x11, 0x4a, 0x6f, 0x62, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x7b, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x41, 0x6e, 0x64, 0x53, 0x61, 0x76, 0x65, 0x64,
	0x4a, 0x6f, 0x62, 0x73, 0x49, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x27, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x71, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x13, 0x53,
	0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce sync.Once
	file_protos_service_job_posting_service_grpc_proto_rawDescData = file_protos_service_job_posting_service_grpc_proto_rawDesc
)

func file_protos_service_job_posting_service_grpc_proto_rawDescGZIP() []byte {
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce.Do(func() {
		file_protos_service_job_posting_service_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_service_job_posting_service_grpc_proto_rawDescData)
	})
	return file_protos_service_job_posting_service_grpc_proto_rawDescData
}

var file_protos_service_job_posting_service_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_service_job_posting_service_grpc_proto_goTypes = []interface{}{
	(*GetJobSeekerJobsRequest)(nil),      // 0: protos.service.GetJobSeekerJobsRequest
	(*GetJobSeekerJobsResponse)(nil),     // 1: protos.service.GetJobSeekerJobsResponse
	(*Job)(nil),                          // 2: protos.service.Job
	(*GetApplicationStatusRequest)(nil),  // 3: protos.service.GetApplicationStatusRequest
	(*GetApplicationStatusResponse)(nil), // 4: protos.service.GetApplicationStatusResponse
	(*GetJobRequest)(nil),                // 5: protos.service.GetJobRequest
	(*GetJobResponse)(nil),               // 6: protos.service.GetJobResponse
	(*domain.JobGrpc)(nil),               // 7: protos.domain.JobGrpc
	(*domain.JobseekerSkill)(nil),        // 8: protos.domain.JobseekerSkill
}
var file_protos_service_job_posting_service_grpc_proto_depIdxs = []int32{
	2, // 0: protos.service.GetJobSeekerJobsResponse.hiddenJobs:type_name -> protos.service.Job
	2, // 1: protos.service.GetJobSeekerJobsResponse.savedJobs:type_name -> protos.service.Job
	7, // 2: protos.service.GetJobResponse.job:type_name -> protos.domain.JobGrpc
	0, // 3: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:input_type -> protos.service.GetJobSeekerJobsRequest
	3, // 4: protos.service.JobPostingService.GetApplicationStatus:input_type -> protos.service.GetApplicationStatusRequest
	5, // 5: protos.service.JobPostingService.GetJob:input_type -> protos.service.GetJobRequest
	8, // 6: protos.service.JobPostingService.SaveJobSeekerSkills:input_type -> protos.domain.JobseekerSkill
	1, // 7: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:output_type -> protos.service.GetJobSeekerJobsResponse
	4, // 8: protos.service.JobPostingService.GetApplicationStatus:output_type -> protos.service.GetApplicationStatusResponse
	6, // 9: protos.service.JobPostingService.GetJob:output_type -> protos.service.GetJobResponse
	8, // 10: protos.service.JobPostingService.SaveJobSeekerSkills:output_type -> protos.domain.JobseekerSkill
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_service_job_posting_service_grpc_proto_init() }
func file_protos_service_job_posting_service_grpc_proto_init() {
	if File_protos_service_job_posting_service_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_service_job_posting_service_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_service_job_posting_service_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_job_posting_service_grpc_proto_goTypes,
		DependencyIndexes: file_protos_service_job_posting_service_grpc_proto_depIdxs,
		MessageInfos:      file_protos_service_job_posting_service_grpc_proto_msgTypes,
	}.Build()
	File_protos_service_job_posting_service_grpc_proto = out.File
	file_protos_service_job_posting_service_grpc_proto_rawDesc = nil
	file_protos_service_job_posting_service_grpc_proto_goTypes = nil
	file_protos_service_job_posting_service_grpc_proto_depIdxs = nil
}
