// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: protos/service/job_posting_service.grpc.proto

package service

import (
	domain "github.com/wanpng/job-posting-grpc/grpc/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobSeekerJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobseekerId string `protobuf:"bytes,1,opt,name=jobseeker_id,json=jobseekerId,proto3" json:"jobseeker_id,omitempty"`
}

func (x *GetJobSeekerJobsRequest) Reset() {
	*x = GetJobSeekerJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsRequest) ProtoMessage() {}

func (x *GetJobSeekerJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsRequest.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobSeekerJobsRequest) GetJobseekerId() string {
	if x != nil {
		return x.JobseekerId
	}
	return ""
}

type SaveJobSeekerSkillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateSkillId string `protobuf:"bytes,1,opt,name=candidate_skill_id,json=candidateSkillId,proto3" json:"candidate_skill_id,omitempty"`
}

func (x *SaveJobSeekerSkillsRequest) Reset() {
	*x = SaveJobSeekerSkillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveJobSeekerSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobSeekerSkillsRequest) ProtoMessage() {}

func (x *SaveJobSeekerSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobSeekerSkillsRequest.ProtoReflect.Descriptor instead.
func (*SaveJobSeekerSkillsRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *SaveJobSeekerSkillsRequest) GetCandidateSkillId() string {
	if x != nil {
		return x.CandidateSkillId
	}
	return ""
}

type GetJobSeekerJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HiddenJobs []*Job `protobuf:"bytes,1,rep,name=hiddenJobs,proto3" json:"hiddenJobs,omitempty"`
	SavedJobs  []*Job `protobuf:"bytes,2,rep,name=savedJobs,proto3" json:"savedJobs,omitempty"`
}

func (x *GetJobSeekerJobsResponse) Reset() {
	*x = GetJobSeekerJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobSeekerJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobSeekerJobsResponse) ProtoMessage() {}

func (x *GetJobSeekerJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobSeekerJobsResponse.ProtoReflect.Descriptor instead.
func (*GetJobSeekerJobsResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobSeekerJobsResponse) GetHiddenJobs() []*Job {
	if x != nil {
		return x.HiddenJobs
	}
	return nil
}

func (x *GetJobSeekerJobsResponse) GetSavedJobs() []*Job {
	if x != nil {
		return x.SavedJobs
	}
	return nil
}

type SaveJobSeekerSkillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateSkills []*CandidateSkill `protobuf:"bytes,1,rep,name=candidateSkills,proto3" json:"candidateSkills,omitempty"`
}

func (x *SaveJobSeekerSkillsResponse) Reset() {
	*x = SaveJobSeekerSkillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveJobSeekerSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobSeekerSkillsResponse) ProtoMessage() {}

func (x *SaveJobSeekerSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobSeekerSkillsResponse.ProtoReflect.Descriptor instead.
func (*SaveJobSeekerSkillsResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *SaveJobSeekerSkillsResponse) GetCandidateSkills() []*CandidateSkill {
	if x != nil {
		return x.CandidateSkills
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CandidateSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId string `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
}

func (x *CandidateSkill) Reset() {
	*x = CandidateSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateSkill) ProtoMessage() {}

func (x *CandidateSkill) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_job_posting_service_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateSkill.ProtoReflect.Descriptor instead.
func (*CandidateSkill) Descriptor() ([]byte, []int) {
	return file_protos_service_job_posting_service_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *CandidateSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

var File_protos_service_job_posting_service_grpc_proto protoreflect.FileDescriptor

var file_protos_service_job_posting_service_grpc_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f,
	0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a, 0x0a,
	0x1a, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e,
	0x4a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52,
	0x0a, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x73,
	0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4a, 0x6f, 0x62, 0x52, 0x09, 0x73, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x67,
	0x0a, 0x1b, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a,
	0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x1c, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x32, 0xed, 0x01, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x41, 0x6e,
	0x64, 0x53, 0x61, 0x76, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x49, 0x6e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x2a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x47, 0x72,
	0x70, 0x63, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x70, 0x6f, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce sync.Once
	file_protos_service_job_posting_service_grpc_proto_rawDescData = file_protos_service_job_posting_service_grpc_proto_rawDesc
)

func file_protos_service_job_posting_service_grpc_proto_rawDescGZIP() []byte {
	file_protos_service_job_posting_service_grpc_proto_rawDescOnce.Do(func() {
		file_protos_service_job_posting_service_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_service_job_posting_service_grpc_proto_rawDescData)
	})
	return file_protos_service_job_posting_service_grpc_proto_rawDescData
}

var file_protos_service_job_posting_service_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_service_job_posting_service_grpc_proto_goTypes = []interface{}{
	(*GetJobSeekerJobsRequest)(nil),     // 0: protos.service.GetJobSeekerJobsRequest
	(*SaveJobSeekerSkillsRequest)(nil),  // 1: protos.service.SaveJobSeekerSkillsRequest
	(*GetJobSeekerJobsResponse)(nil),    // 2: protos.service.GetJobSeekerJobsResponse
	(*SaveJobSeekerSkillsResponse)(nil), // 3: protos.service.SaveJobSeekerSkillsResponse
	(*Job)(nil),                         // 4: protos.service.Job
	(*CandidateSkill)(nil),              // 5: protos.service.CandidateSkill
	(*domain.ErrorGrpc)(nil),            // 6: protos.domain.ErrorGrpc
}
var file_protos_service_job_posting_service_grpc_proto_depIdxs = []int32{
	4, // 0: protos.service.GetJobSeekerJobsResponse.hiddenJobs:type_name -> protos.service.Job
	4, // 1: protos.service.GetJobSeekerJobsResponse.savedJobs:type_name -> protos.service.Job
	5, // 2: protos.service.SaveJobSeekerSkillsResponse.candidateSkills:type_name -> protos.service.CandidateSkill
	0, // 3: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:input_type -> protos.service.GetJobSeekerJobsRequest
	1, // 4: protos.service.JobPostingService.SaveJobSeekerSkills:input_type -> protos.service.SaveJobSeekerSkillsRequest
	2, // 5: protos.service.JobPostingService.GetJobSeekerHiddenAndSavedJobsInSearch:output_type -> protos.service.GetJobSeekerJobsResponse
	6, // 6: protos.service.JobPostingService.SaveJobSeekerSkills:output_type -> protos.domain.ErrorGrpc
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_service_job_posting_service_grpc_proto_init() }
func file_protos_service_job_posting_service_grpc_proto_init() {
	if File_protos_service_job_posting_service_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_service_job_posting_service_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveJobSeekerSkillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobSeekerJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveJobSeekerSkillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_job_posting_service_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidateSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_service_job_posting_service_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_job_posting_service_grpc_proto_goTypes,
		DependencyIndexes: file_protos_service_job_posting_service_grpc_proto_depIdxs,
		MessageInfos:      file_protos_service_job_posting_service_grpc_proto_msgTypes,
	}.Build()
	File_protos_service_job_posting_service_grpc_proto = out.File
	file_protos_service_job_posting_service_grpc_proto_rawDesc = nil
	file_protos_service_job_posting_service_grpc_proto_goTypes = nil
	file_protos_service_job_posting_service_grpc_proto_depIdxs = nil
}
