// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

/**
 * Protobuf type {@code protos.service.GetJobResponse}
 */
public final class GetJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.GetJobResponse)
    GetJobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetJobResponse.newBuilder() to construct.
  private GetJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetJobResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetJobResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetJobResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.wanpng.jobposting.grpc.domain.JobGrpc.Builder subBuilder = null;
            if (job_ != null) {
              subBuilder = job_.toBuilder();
            }
            job_ = input.readMessage(com.wanpng.jobposting.grpc.domain.JobGrpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(job_);
              job_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_GetJobResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_GetJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobposting.grpc.service.GetJobResponse.class, com.wanpng.jobposting.grpc.service.GetJobResponse.Builder.class);
  }

  public static final int JOB_FIELD_NUMBER = 1;
  private com.wanpng.jobposting.grpc.domain.JobGrpc job_;
  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   * @return Whether the job field is set.
   */
  @java.lang.Override
  public boolean hasJob() {
    return job_ != null;
  }
  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   * @return The job.
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.JobGrpc getJob() {
    return job_ == null ? com.wanpng.jobposting.grpc.domain.JobGrpc.getDefaultInstance() : job_;
  }
  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder getJobOrBuilder() {
    return getJob();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (job_ != null) {
      output.writeMessage(1, getJob());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (job_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getJob());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobposting.grpc.service.GetJobResponse)) {
      return super.equals(obj);
    }
    com.wanpng.jobposting.grpc.service.GetJobResponse other = (com.wanpng.jobposting.grpc.service.GetJobResponse) obj;

    if (hasJob() != other.hasJob()) return false;
    if (hasJob()) {
      if (!getJob()
          .equals(other.getJob())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJob()) {
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + getJob().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.GetJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobposting.grpc.service.GetJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.GetJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.GetJobResponse)
      com.wanpng.jobposting.grpc.service.GetJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_GetJobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_GetJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobposting.grpc.service.GetJobResponse.class, com.wanpng.jobposting.grpc.service.GetJobResponse.Builder.class);
    }

    // Construct using com.wanpng.jobposting.grpc.service.GetJobResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobBuilder_ == null) {
        job_ = null;
      } else {
        job_ = null;
        jobBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_GetJobResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.GetJobResponse getDefaultInstanceForType() {
      return com.wanpng.jobposting.grpc.service.GetJobResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.GetJobResponse build() {
      com.wanpng.jobposting.grpc.service.GetJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.GetJobResponse buildPartial() {
      com.wanpng.jobposting.grpc.service.GetJobResponse result = new com.wanpng.jobposting.grpc.service.GetJobResponse(this);
      if (jobBuilder_ == null) {
        result.job_ = job_;
      } else {
        result.job_ = jobBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobposting.grpc.service.GetJobResponse) {
        return mergeFrom((com.wanpng.jobposting.grpc.service.GetJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobposting.grpc.service.GetJobResponse other) {
      if (other == com.wanpng.jobposting.grpc.service.GetJobResponse.getDefaultInstance()) return this;
      if (other.hasJob()) {
        mergeJob(other.getJob());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobposting.grpc.service.GetJobResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobposting.grpc.service.GetJobResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wanpng.jobposting.grpc.domain.JobGrpc job_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.JobGrpc, com.wanpng.jobposting.grpc.domain.JobGrpc.Builder, com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder> jobBuilder_;
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     * @return Whether the job field is set.
     */
    public boolean hasJob() {
      return jobBuilder_ != null || job_ != null;
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     * @return The job.
     */
    public com.wanpng.jobposting.grpc.domain.JobGrpc getJob() {
      if (jobBuilder_ == null) {
        return job_ == null ? com.wanpng.jobposting.grpc.domain.JobGrpc.getDefaultInstance() : job_;
      } else {
        return jobBuilder_.getMessage();
      }
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public Builder setJob(com.wanpng.jobposting.grpc.domain.JobGrpc value) {
      if (jobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        job_ = value;
        onChanged();
      } else {
        jobBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public Builder setJob(
        com.wanpng.jobposting.grpc.domain.JobGrpc.Builder builderForValue) {
      if (jobBuilder_ == null) {
        job_ = builderForValue.build();
        onChanged();
      } else {
        jobBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public Builder mergeJob(com.wanpng.jobposting.grpc.domain.JobGrpc value) {
      if (jobBuilder_ == null) {
        if (job_ != null) {
          job_ =
            com.wanpng.jobposting.grpc.domain.JobGrpc.newBuilder(job_).mergeFrom(value).buildPartial();
        } else {
          job_ = value;
        }
        onChanged();
      } else {
        jobBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public Builder clearJob() {
      if (jobBuilder_ == null) {
        job_ = null;
        onChanged();
      } else {
        job_ = null;
        jobBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public com.wanpng.jobposting.grpc.domain.JobGrpc.Builder getJobBuilder() {
      
      onChanged();
      return getJobFieldBuilder().getBuilder();
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    public com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder getJobOrBuilder() {
      if (jobBuilder_ != null) {
        return jobBuilder_.getMessageOrBuilder();
      } else {
        return job_ == null ?
            com.wanpng.jobposting.grpc.domain.JobGrpc.getDefaultInstance() : job_;
      }
    }
    /**
     * <code>.protos.domain.JobGrpc job = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.JobGrpc, com.wanpng.jobposting.grpc.domain.JobGrpc.Builder, com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder> 
        getJobFieldBuilder() {
      if (jobBuilder_ == null) {
        jobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wanpng.jobposting.grpc.domain.JobGrpc, com.wanpng.jobposting.grpc.domain.JobGrpc.Builder, com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder>(
                getJob(),
                getParentForChildren(),
                isClean());
        job_ = null;
      }
      return jobBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.GetJobResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.GetJobResponse)
  private static final com.wanpng.jobposting.grpc.service.GetJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobposting.grpc.service.GetJobResponse();
  }

  public static com.wanpng.jobposting.grpc.service.GetJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetJobResponse>() {
    @java.lang.Override
    public GetJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetJobResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetJobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetJobResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobposting.grpc.service.GetJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

