// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

public interface GetJobsByEmployerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetJobsByEmployerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employer_id = 1;</code>
   * @return The employerId.
   */
  java.lang.String getEmployerId();
  /**
   * <code>string employer_id = 1;</code>
   * @return The bytes for employerId.
   */
  com.google.protobuf.ByteString
      getEmployerIdBytes();

  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string photo = 3;</code>
   * @return The photo.
   */
  java.lang.String getPhoto();
  /**
   * <code>string photo = 3;</code>
   * @return The bytes for photo.
   */
  com.google.protobuf.ByteString
      getPhotoBytes();

  /**
   * <code>bool is_lanco = 4;</code>
   * @return The isLanco.
   */
  boolean getIsLanco();
}
