// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

public interface GetJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   * @return The job.
   */
  com.wanpng.jobposting.grpc.domain.JobGrpc getJob();
  /**
   * <code>.protos.domain.JobGrpc job = 1;</code>
   */
  com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder getJobOrBuilder();
}
