// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

public interface GetJobUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetJobUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   * @return The user.
   */
  com.wanpng.jobposting.grpc.domain.UserGrpc getUser();
  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   */
  com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder getUserOrBuilder();
}
