// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
