// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

public interface SearchJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.SearchJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string employer_ids = 1;</code>
   * @return A list containing the employerIds.
   */
  java.util.List<java.lang.String>
      getEmployerIdsList();
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @return The count of employerIds.
   */
  int getEmployerIdsCount();
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The employerIds at the given index.
   */
  java.lang.String getEmployerIds(int index);
  /**
   * <code>repeated string employer_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the employerIds at the given index.
   */
  com.google.protobuf.ByteString
      getEmployerIdsBytes(int index);

  /**
   * <code>string keyword = 2;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <code>string keyword = 2;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();
}
