// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

/**
 * Protobuf type {@code protos.service.SearchJobResponse}
 */
public final class SearchJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.SearchJobResponse)
    SearchJobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchJobResponse.newBuilder() to construct.
  private SearchJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchJobResponse() {
    jobIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchJobResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchJobResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            jobIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobIds_ = jobIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_SearchJobResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_SearchJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobposting.grpc.service.SearchJobResponse.class, com.wanpng.jobposting.grpc.service.SearchJobResponse.Builder.class);
  }

  public static final int JOB_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList jobIds_;
  /**
   * <code>repeated string job_ids = 1;</code>
   * @return A list containing the jobIds.
   */
  public com.google.protobuf.ProtocolStringList
      getJobIdsList() {
    return jobIds_;
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @return The count of jobIds.
   */
  public int getJobIdsCount() {
    return jobIds_.size();
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The jobIds at the given index.
   */
  public java.lang.String getJobIds(int index) {
    return jobIds_.get(index);
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jobIds at the given index.
   */
  public com.google.protobuf.ByteString
      getJobIdsBytes(int index) {
    return jobIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < jobIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(jobIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getJobIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobposting.grpc.service.SearchJobResponse)) {
      return super.equals(obj);
    }
    com.wanpng.jobposting.grpc.service.SearchJobResponse other = (com.wanpng.jobposting.grpc.service.SearchJobResponse) obj;

    if (!getJobIdsList()
        .equals(other.getJobIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobIdsCount() > 0) {
      hash = (37 * hash) + JOB_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getJobIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.SearchJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobposting.grpc.service.SearchJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.SearchJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.SearchJobResponse)
      com.wanpng.jobposting.grpc.service.SearchJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_SearchJobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_SearchJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobposting.grpc.service.SearchJobResponse.class, com.wanpng.jobposting.grpc.service.SearchJobResponse.Builder.class);
    }

    // Construct using com.wanpng.jobposting.grpc.service.SearchJobResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      jobIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_SearchJobResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.SearchJobResponse getDefaultInstanceForType() {
      return com.wanpng.jobposting.grpc.service.SearchJobResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.SearchJobResponse build() {
      com.wanpng.jobposting.grpc.service.SearchJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.SearchJobResponse buildPartial() {
      com.wanpng.jobposting.grpc.service.SearchJobResponse result = new com.wanpng.jobposting.grpc.service.SearchJobResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        jobIds_ = jobIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.jobIds_ = jobIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobposting.grpc.service.SearchJobResponse) {
        return mergeFrom((com.wanpng.jobposting.grpc.service.SearchJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobposting.grpc.service.SearchJobResponse other) {
      if (other == com.wanpng.jobposting.grpc.service.SearchJobResponse.getDefaultInstance()) return this;
      if (!other.jobIds_.isEmpty()) {
        if (jobIds_.isEmpty()) {
          jobIds_ = other.jobIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureJobIdsIsMutable();
          jobIds_.addAll(other.jobIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobposting.grpc.service.SearchJobResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobposting.grpc.service.SearchJobResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList jobIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureJobIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobIds_ = new com.google.protobuf.LazyStringArrayList(jobIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return A list containing the jobIds.
     */
    public com.google.protobuf.ProtocolStringList
        getJobIdsList() {
      return jobIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return The count of jobIds.
     */
    public int getJobIdsCount() {
      return jobIds_.size();
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The jobIds at the given index.
     */
    public java.lang.String getJobIds(int index) {
      return jobIds_.get(index);
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the jobIds at the given index.
     */
    public com.google.protobuf.ByteString
        getJobIdsBytes(int index) {
      return jobIds_.getByteString(index);
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The jobIds to set.
     * @return This builder for chaining.
     */
    public Builder setJobIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureJobIdsIsMutable();
      jobIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param value The jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addJobIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureJobIdsIsMutable();
      jobIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param values The jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllJobIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureJobIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, jobIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobIds() {
      jobIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param value The bytes of the jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addJobIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureJobIdsIsMutable();
      jobIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.SearchJobResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.SearchJobResponse)
  private static final com.wanpng.jobposting.grpc.service.SearchJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobposting.grpc.service.SearchJobResponse();
  }

  public static com.wanpng.jobposting.grpc.service.SearchJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchJobResponse>() {
    @java.lang.Override
    public SearchJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchJobResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchJobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchJobResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobposting.grpc.service.SearchJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

