// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.jobposting.grpc.service;

/**
 * Protobuf type {@code protos.service.UpdateJobUserRequest}
 */
public final class UpdateJobUserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.UpdateJobUserRequest)
    UpdateJobUserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateJobUserRequest.newBuilder() to construct.
  private UpdateJobUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateJobUserRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateJobUserRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateJobUserRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.wanpng.jobposting.grpc.domain.UserGrpc.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.wanpng.jobposting.grpc.domain.UserGrpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_UpdateJobUserRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_UpdateJobUserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.class, com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.wanpng.jobposting.grpc.domain.UserGrpc user_;
  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   * @return The user.
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.UserGrpc getUser() {
    return user_ == null ? com.wanpng.jobposting.grpc.domain.UserGrpc.getDefaultInstance() : user_;
  }
  /**
   * <code>.protos.domain.UserGrpc user = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder getUserOrBuilder() {
    return getUser();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobposting.grpc.service.UpdateJobUserRequest)) {
      return super.equals(obj);
    }
    com.wanpng.jobposting.grpc.service.UpdateJobUserRequest other = (com.wanpng.jobposting.grpc.service.UpdateJobUserRequest) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobposting.grpc.service.UpdateJobUserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.UpdateJobUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.UpdateJobUserRequest)
      com.wanpng.jobposting.grpc.service.UpdateJobUserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_UpdateJobUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_UpdateJobUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.class, com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.Builder.class);
    }

    // Construct using com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobposting.grpc.service.JobPostingServiceProtos.internal_static_protos_service_UpdateJobUserRequest_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.UpdateJobUserRequest getDefaultInstanceForType() {
      return com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.UpdateJobUserRequest build() {
      com.wanpng.jobposting.grpc.service.UpdateJobUserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.service.UpdateJobUserRequest buildPartial() {
      com.wanpng.jobposting.grpc.service.UpdateJobUserRequest result = new com.wanpng.jobposting.grpc.service.UpdateJobUserRequest(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobposting.grpc.service.UpdateJobUserRequest) {
        return mergeFrom((com.wanpng.jobposting.grpc.service.UpdateJobUserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobposting.grpc.service.UpdateJobUserRequest other) {
      if (other == com.wanpng.jobposting.grpc.service.UpdateJobUserRequest.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobposting.grpc.service.UpdateJobUserRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobposting.grpc.service.UpdateJobUserRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wanpng.jobposting.grpc.domain.UserGrpc user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.UserGrpc, com.wanpng.jobposting.grpc.domain.UserGrpc.Builder, com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder> userBuilder_;
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     * @return The user.
     */
    public com.wanpng.jobposting.grpc.domain.UserGrpc getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.wanpng.jobposting.grpc.domain.UserGrpc.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public Builder setUser(com.wanpng.jobposting.grpc.domain.UserGrpc value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public Builder setUser(
        com.wanpng.jobposting.grpc.domain.UserGrpc.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public Builder mergeUser(com.wanpng.jobposting.grpc.domain.UserGrpc value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.wanpng.jobposting.grpc.domain.UserGrpc.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public com.wanpng.jobposting.grpc.domain.UserGrpc.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    public com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.wanpng.jobposting.grpc.domain.UserGrpc.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.protos.domain.UserGrpc user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.UserGrpc, com.wanpng.jobposting.grpc.domain.UserGrpc.Builder, com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wanpng.jobposting.grpc.domain.UserGrpc, com.wanpng.jobposting.grpc.domain.UserGrpc.Builder, com.wanpng.jobposting.grpc.domain.UserGrpcOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.UpdateJobUserRequest)
  }

  // @@protoc_insertion_point(class_scope:protos.service.UpdateJobUserRequest)
  private static final com.wanpng.jobposting.grpc.service.UpdateJobUserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobposting.grpc.service.UpdateJobUserRequest();
  }

  public static com.wanpng.jobposting.grpc.service.UpdateJobUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateJobUserRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateJobUserRequest>() {
    @java.lang.Override
    public UpdateJobUserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateJobUserRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateJobUserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateJobUserRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobposting.grpc.service.UpdateJobUserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

