// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/candidateskills.grpc.proto

package com.wanpng.jobposting.grpc.domain;

public interface CandidateSkillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.CandidateSkill)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string skill_id = 1;</code>
   * @return The skillId.
   */
  java.lang.String getSkillId();
  /**
   * <code>string skill_id = 1;</code>
   * @return The bytes for skillId.
   */
  com.google.protobuf.ByteString
      getSkillIdBytes();

  /**
   * <code>string skill = 2;</code>
   * @return The skill.
   */
  java.lang.String getSkill();
  /**
   * <code>string skill = 2;</code>
   * @return The bytes for skill.
   */
  com.google.protobuf.ByteString
      getSkillBytes();

  /**
   * <code>int32 level_id = 3;</code>
   * @return The levelId.
   */
  int getLevelId();

  /**
   * <code>string level = 4;</code>
   * @return The level.
   */
  java.lang.String getLevel();
  /**
   * <code>string level = 4;</code>
   * @return The bytes for level.
   */
  com.google.protobuf.ByteString
      getLevelBytes();
}
