// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/candidateskills.grpc.proto

package com.wanpng.jobposting.grpc.domain;

/**
 * Protobuf type {@code protos.domain.CandidateSkills}
 */
public final class CandidateSkills extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.CandidateSkills)
    CandidateSkillsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CandidateSkills.newBuilder() to construct.
  private CandidateSkills(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CandidateSkills() {
    id_ = "";
    skills_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CandidateSkills();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CandidateSkills(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skills_ = new java.util.ArrayList<com.wanpng.jobposting.grpc.domain.CandidateSkill>();
              mutable_bitField0_ |= 0x00000001;
            }
            skills_.add(
                input.readMessage(com.wanpng.jobposting.grpc.domain.CandidateSkill.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skills_ = java.util.Collections.unmodifiableList(skills_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobposting.grpc.domain.CandidateSkillProtos.internal_static_protos_domain_CandidateSkills_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobposting.grpc.domain.CandidateSkillProtos.internal_static_protos_domain_CandidateSkills_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobposting.grpc.domain.CandidateSkills.class, com.wanpng.jobposting.grpc.domain.CandidateSkills.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKILLS_FIELD_NUMBER = 2;
  private java.util.List<com.wanpng.jobposting.grpc.domain.CandidateSkill> skills_;
  /**
   * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.jobposting.grpc.domain.CandidateSkill> getSkillsList() {
    return skills_;
  }
  /**
   * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder> 
      getSkillsOrBuilderList() {
    return skills_;
  }
  /**
   * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
   */
  @java.lang.Override
  public int getSkillsCount() {
    return skills_.size();
  }
  /**
   * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.CandidateSkill getSkills(int index) {
    return skills_.get(index);
  }
  /**
   * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
   */
  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder getSkillsOrBuilder(
      int index) {
    return skills_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < skills_.size(); i++) {
      output.writeMessage(2, skills_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < skills_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, skills_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobposting.grpc.domain.CandidateSkills)) {
      return super.equals(obj);
    }
    com.wanpng.jobposting.grpc.domain.CandidateSkills other = (com.wanpng.jobposting.grpc.domain.CandidateSkills) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getSkillsList()
        .equals(other.getSkillsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getSkillsCount() > 0) {
      hash = (37 * hash) + SKILLS_FIELD_NUMBER;
      hash = (53 * hash) + getSkillsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.CandidateSkills parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobposting.grpc.domain.CandidateSkills prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.CandidateSkills}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.CandidateSkills)
      com.wanpng.jobposting.grpc.domain.CandidateSkillsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobposting.grpc.domain.CandidateSkillProtos.internal_static_protos_domain_CandidateSkills_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobposting.grpc.domain.CandidateSkillProtos.internal_static_protos_domain_CandidateSkills_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobposting.grpc.domain.CandidateSkills.class, com.wanpng.jobposting.grpc.domain.CandidateSkills.Builder.class);
    }

    // Construct using com.wanpng.jobposting.grpc.domain.CandidateSkills.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSkillsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (skillsBuilder_ == null) {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        skillsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobposting.grpc.domain.CandidateSkillProtos.internal_static_protos_domain_CandidateSkills_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.CandidateSkills getDefaultInstanceForType() {
      return com.wanpng.jobposting.grpc.domain.CandidateSkills.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.CandidateSkills build() {
      com.wanpng.jobposting.grpc.domain.CandidateSkills result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.CandidateSkills buildPartial() {
      com.wanpng.jobposting.grpc.domain.CandidateSkills result = new com.wanpng.jobposting.grpc.domain.CandidateSkills(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (skillsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
      } else {
        result.skills_ = skillsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobposting.grpc.domain.CandidateSkills) {
        return mergeFrom((com.wanpng.jobposting.grpc.domain.CandidateSkills)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobposting.grpc.domain.CandidateSkills other) {
      if (other == com.wanpng.jobposting.grpc.domain.CandidateSkills.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (skillsBuilder_ == null) {
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
      } else {
        if (!other.skills_.isEmpty()) {
          if (skillsBuilder_.isEmpty()) {
            skillsBuilder_.dispose();
            skillsBuilder_ = null;
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
            skillsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkillsFieldBuilder() : null;
          } else {
            skillsBuilder_.addAllMessages(other.skills_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobposting.grpc.domain.CandidateSkills parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobposting.grpc.domain.CandidateSkills) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.wanpng.jobposting.grpc.domain.CandidateSkill> skills_ =
      java.util.Collections.emptyList();
    private void ensureSkillsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skills_ = new java.util.ArrayList<com.wanpng.jobposting.grpc.domain.CandidateSkill>(skills_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.CandidateSkill, com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder, com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder> skillsBuilder_;

    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public java.util.List<com.wanpng.jobposting.grpc.domain.CandidateSkill> getSkillsList() {
      if (skillsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(skills_);
      } else {
        return skillsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public int getSkillsCount() {
      if (skillsBuilder_ == null) {
        return skills_.size();
      } else {
        return skillsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public com.wanpng.jobposting.grpc.domain.CandidateSkill getSkills(int index) {
      if (skillsBuilder_ == null) {
        return skills_.get(index);
      } else {
        return skillsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder setSkills(
        int index, com.wanpng.jobposting.grpc.domain.CandidateSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
      } else {
        skillsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder setSkills(
        int index, com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.set(index, builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder addSkills(com.wanpng.jobposting.grpc.domain.CandidateSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
      } else {
        skillsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder addSkills(
        int index, com.wanpng.jobposting.grpc.domain.CandidateSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(index, value);
        onChanged();
      } else {
        skillsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder addSkills(
        com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.add(builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder addSkills(
        int index, com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.add(index, builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder addAllSkills(
        java.lang.Iterable<? extends com.wanpng.jobposting.grpc.domain.CandidateSkill> values) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
      } else {
        skillsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder clearSkills() {
      if (skillsBuilder_ == null) {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        skillsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public Builder removeSkills(int index) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.remove(index);
        onChanged();
      } else {
        skillsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder getSkillsBuilder(
        int index) {
      return getSkillsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder getSkillsOrBuilder(
        int index) {
      if (skillsBuilder_ == null) {
        return skills_.get(index);  } else {
        return skillsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public java.util.List<? extends com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder> 
         getSkillsOrBuilderList() {
      if (skillsBuilder_ != null) {
        return skillsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(skills_);
      }
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder addSkillsBuilder() {
      return getSkillsFieldBuilder().addBuilder(
          com.wanpng.jobposting.grpc.domain.CandidateSkill.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder addSkillsBuilder(
        int index) {
      return getSkillsFieldBuilder().addBuilder(
          index, com.wanpng.jobposting.grpc.domain.CandidateSkill.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.CandidateSkill skills = 2;</code>
     */
    public java.util.List<com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder> 
         getSkillsBuilderList() {
      return getSkillsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobposting.grpc.domain.CandidateSkill, com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder, com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder> 
        getSkillsFieldBuilder() {
      if (skillsBuilder_ == null) {
        skillsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.jobposting.grpc.domain.CandidateSkill, com.wanpng.jobposting.grpc.domain.CandidateSkill.Builder, com.wanpng.jobposting.grpc.domain.CandidateSkillOrBuilder>(
                skills_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        skills_ = null;
      }
      return skillsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.CandidateSkills)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.CandidateSkills)
  private static final com.wanpng.jobposting.grpc.domain.CandidateSkills DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobposting.grpc.domain.CandidateSkills();
  }

  public static com.wanpng.jobposting.grpc.domain.CandidateSkills getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CandidateSkills>
      PARSER = new com.google.protobuf.AbstractParser<CandidateSkills>() {
    @java.lang.Override
    public CandidateSkills parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CandidateSkills(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CandidateSkills> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CandidateSkills> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.CandidateSkills getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

