// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/candidateskills.grpc.proto

package com.wanpng.jobposting.grpc.domain;

public final class CandidateSkillProtos {
  private CandidateSkillProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_CandidateSkill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_CandidateSkill_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_CandidateSkills_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_CandidateSkills_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(protos/domain/candidateskills.grpc.pro" +
      "to\022\rprotos.domain\"R\n\016CandidateSkill\022\020\n\010s" +
      "kill_id\030\001 \001(\t\022\r\n\005skill\030\002 \001(\t\022\020\n\010level_id" +
      "\030\003 \001(\005\022\r\n\005level\030\004 \001(\t\"L\n\017CandidateSkills" +
      "\022\n\n\002id\030\001 \001(\t\022-\n\006skills\030\002 \003(\0132\035.protos.do" +
      "main.CandidateSkillBk\n!com.wanpng.jobpos" +
      "ting.grpc.domainB\024CandidateSkillProtosP\001" +
      "Z.github.com/wanpng/job-posting-grpc/grp" +
      "c/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_CandidateSkill_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_CandidateSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_CandidateSkill_descriptor,
        new java.lang.String[] { "SkillId", "Skill", "LevelId", "Level", });
    internal_static_protos_domain_CandidateSkills_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_domain_CandidateSkills_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_CandidateSkills_descriptor,
        new java.lang.String[] { "Id", "Skills", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
