// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/job.grpc.proto

package com.wanpng.jobposting.grpc.domain;

/**
 * Protobuf type {@code protos.domain.JobGrpc}
 */
public final class JobGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.JobGrpc)
    JobGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobGrpc.newBuilder() to construct.
  private JobGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobGrpc() {
    id_ = "";
    jobTitle_ = "";
    employmentType_ = "";
    careerLevel_ = "";
    province_ = "";
    publishStatus_ = "";
    createdBy_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            jobTitle_ = s;
            break;
          }
          case 24: {

            employmentTypeId_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            employmentType_ = s;
            break;
          }
          case 40: {

            careerLevelId_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            careerLevel_ = s;
            break;
          }
          case 56: {

            provinceId_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 72: {

            publishStatusId_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            publishStatus_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            createdBy_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobposting.grpc.domain.JobGrpcProtos.internal_static_protos_domain_JobGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobposting.grpc.domain.JobGrpcProtos.internal_static_protos_domain_JobGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobposting.grpc.domain.JobGrpc.class, com.wanpng.jobposting.grpc.domain.JobGrpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object jobTitle_;
  /**
   * <code>string job_title = 2;</code>
   * @return The jobTitle.
   */
  @java.lang.Override
  public java.lang.String getJobTitle() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string job_title = 2;</code>
   * @return The bytes for jobTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobTitleBytes() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYMENT_TYPE_ID_FIELD_NUMBER = 3;
  private int employmentTypeId_;
  /**
   * <code>int32 employment_type_id = 3;</code>
   * @return The employmentTypeId.
   */
  @java.lang.Override
  public int getEmploymentTypeId() {
    return employmentTypeId_;
  }

  public static final int EMPLOYMENT_TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object employmentType_;
  /**
   * <code>string employment_type = 4;</code>
   * @return The employmentType.
   */
  @java.lang.Override
  public java.lang.String getEmploymentType() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employmentType_ = s;
      return s;
    }
  }
  /**
   * <code>string employment_type = 4;</code>
   * @return The bytes for employmentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmploymentTypeBytes() {
    java.lang.Object ref = employmentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employmentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAREER_LEVEL_ID_FIELD_NUMBER = 5;
  private int careerLevelId_;
  /**
   * <code>int32 career_level_id = 5;</code>
   * @return The careerLevelId.
   */
  @java.lang.Override
  public int getCareerLevelId() {
    return careerLevelId_;
  }

  public static final int CAREER_LEVEL_FIELD_NUMBER = 6;
  private volatile java.lang.Object careerLevel_;
  /**
   * <code>string career_level = 6;</code>
   * @return The careerLevel.
   */
  @java.lang.Override
  public java.lang.String getCareerLevel() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      careerLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string career_level = 6;</code>
   * @return The bytes for careerLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCareerLevelBytes() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      careerLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_ID_FIELD_NUMBER = 7;
  private int provinceId_;
  /**
   * <code>int32 province_id = 7;</code>
   * @return The provinceId.
   */
  @java.lang.Override
  public int getProvinceId() {
    return provinceId_;
  }

  public static final int PROVINCE_FIELD_NUMBER = 8;
  private volatile java.lang.Object province_;
  /**
   * <code>string province = 8;</code>
   * @return The province.
   */
  @java.lang.Override
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>string province = 8;</code>
   * @return The bytes for province.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLISH_STATUS_ID_FIELD_NUMBER = 9;
  private int publishStatusId_;
  /**
   * <code>int32 publish_status_id = 9;</code>
   * @return The publishStatusId.
   */
  @java.lang.Override
  public int getPublishStatusId() {
    return publishStatusId_;
  }

  public static final int PUBLISH_STATUS_FIELD_NUMBER = 10;
  private volatile java.lang.Object publishStatus_;
  /**
   * <code>string publish_status = 10;</code>
   * @return The publishStatus.
   */
  @java.lang.Override
  public java.lang.String getPublishStatus() {
    java.lang.Object ref = publishStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      publishStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string publish_status = 10;</code>
   * @return The bytes for publishStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublishStatusBytes() {
    java.lang.Object ref = publishStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publishStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDBY_FIELD_NUMBER = 11;
  private volatile java.lang.Object createdBy_;
  /**
   * <code>string createdBy = 11;</code>
   * @return The createdBy.
   */
  @java.lang.Override
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string createdBy = 11;</code>
   * @return The bytes for createdBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getJobTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jobTitle_);
    }
    if (employmentTypeId_ != 0) {
      output.writeInt32(3, employmentTypeId_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, employmentType_);
    }
    if (careerLevelId_ != 0) {
      output.writeInt32(5, careerLevelId_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, careerLevel_);
    }
    if (provinceId_ != 0) {
      output.writeInt32(7, provinceId_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, province_);
    }
    if (publishStatusId_ != 0) {
      output.writeInt32(9, publishStatusId_);
    }
    if (!getPublishStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, publishStatus_);
    }
    if (!getCreatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, createdBy_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getJobTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jobTitle_);
    }
    if (employmentTypeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, employmentTypeId_);
    }
    if (!getEmploymentTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, employmentType_);
    }
    if (careerLevelId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, careerLevelId_);
    }
    if (!getCareerLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, careerLevel_);
    }
    if (provinceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, provinceId_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, province_);
    }
    if (publishStatusId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, publishStatusId_);
    }
    if (!getPublishStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, publishStatus_);
    }
    if (!getCreatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, createdBy_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobposting.grpc.domain.JobGrpc)) {
      return super.equals(obj);
    }
    com.wanpng.jobposting.grpc.domain.JobGrpc other = (com.wanpng.jobposting.grpc.domain.JobGrpc) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getJobTitle()
        .equals(other.getJobTitle())) return false;
    if (getEmploymentTypeId()
        != other.getEmploymentTypeId()) return false;
    if (!getEmploymentType()
        .equals(other.getEmploymentType())) return false;
    if (getCareerLevelId()
        != other.getCareerLevelId()) return false;
    if (!getCareerLevel()
        .equals(other.getCareerLevel())) return false;
    if (getProvinceId()
        != other.getProvinceId()) return false;
    if (!getProvince()
        .equals(other.getProvince())) return false;
    if (getPublishStatusId()
        != other.getPublishStatusId()) return false;
    if (!getPublishStatus()
        .equals(other.getPublishStatus())) return false;
    if (!getCreatedBy()
        .equals(other.getCreatedBy())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + JOB_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getJobTitle().hashCode();
    hash = (37 * hash) + EMPLOYMENT_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEmploymentTypeId();
    hash = (37 * hash) + EMPLOYMENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEmploymentType().hashCode();
    hash = (37 * hash) + CAREER_LEVEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevelId();
    hash = (37 * hash) + CAREER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevel().hashCode();
    hash = (37 * hash) + PROVINCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProvinceId();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + PUBLISH_STATUS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPublishStatusId();
    hash = (37 * hash) + PUBLISH_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getPublishStatus().hashCode();
    hash = (37 * hash) + CREATEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobposting.grpc.domain.JobGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobposting.grpc.domain.JobGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.JobGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.JobGrpc)
      com.wanpng.jobposting.grpc.domain.JobGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobposting.grpc.domain.JobGrpcProtos.internal_static_protos_domain_JobGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobposting.grpc.domain.JobGrpcProtos.internal_static_protos_domain_JobGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobposting.grpc.domain.JobGrpc.class, com.wanpng.jobposting.grpc.domain.JobGrpc.Builder.class);
    }

    // Construct using com.wanpng.jobposting.grpc.domain.JobGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      jobTitle_ = "";

      employmentTypeId_ = 0;

      employmentType_ = "";

      careerLevelId_ = 0;

      careerLevel_ = "";

      provinceId_ = 0;

      province_ = "";

      publishStatusId_ = 0;

      publishStatus_ = "";

      createdBy_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobposting.grpc.domain.JobGrpcProtos.internal_static_protos_domain_JobGrpc_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.JobGrpc getDefaultInstanceForType() {
      return com.wanpng.jobposting.grpc.domain.JobGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.JobGrpc build() {
      com.wanpng.jobposting.grpc.domain.JobGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobposting.grpc.domain.JobGrpc buildPartial() {
      com.wanpng.jobposting.grpc.domain.JobGrpc result = new com.wanpng.jobposting.grpc.domain.JobGrpc(this);
      result.id_ = id_;
      result.jobTitle_ = jobTitle_;
      result.employmentTypeId_ = employmentTypeId_;
      result.employmentType_ = employmentType_;
      result.careerLevelId_ = careerLevelId_;
      result.careerLevel_ = careerLevel_;
      result.provinceId_ = provinceId_;
      result.province_ = province_;
      result.publishStatusId_ = publishStatusId_;
      result.publishStatus_ = publishStatus_;
      result.createdBy_ = createdBy_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobposting.grpc.domain.JobGrpc) {
        return mergeFrom((com.wanpng.jobposting.grpc.domain.JobGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobposting.grpc.domain.JobGrpc other) {
      if (other == com.wanpng.jobposting.grpc.domain.JobGrpc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getJobTitle().isEmpty()) {
        jobTitle_ = other.jobTitle_;
        onChanged();
      }
      if (other.getEmploymentTypeId() != 0) {
        setEmploymentTypeId(other.getEmploymentTypeId());
      }
      if (!other.getEmploymentType().isEmpty()) {
        employmentType_ = other.employmentType_;
        onChanged();
      }
      if (other.getCareerLevelId() != 0) {
        setCareerLevelId(other.getCareerLevelId());
      }
      if (!other.getCareerLevel().isEmpty()) {
        careerLevel_ = other.careerLevel_;
        onChanged();
      }
      if (other.getProvinceId() != 0) {
        setProvinceId(other.getProvinceId());
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (other.getPublishStatusId() != 0) {
        setPublishStatusId(other.getPublishStatusId());
      }
      if (!other.getPublishStatus().isEmpty()) {
        publishStatus_ = other.publishStatus_;
        onChanged();
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobposting.grpc.domain.JobGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobposting.grpc.domain.JobGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobTitle_ = "";
    /**
     * <code>string job_title = 2;</code>
     * @return The jobTitle.
     */
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_title = 2;</code>
     * @return The bytes for jobTitle.
     */
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_title = 2;</code>
     * @param value The jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobTitle() {
      
      jobTitle_ = getDefaultInstance().getJobTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string job_title = 2;</code>
     * @param value The bytes for jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobTitle_ = value;
      onChanged();
      return this;
    }

    private int employmentTypeId_ ;
    /**
     * <code>int32 employment_type_id = 3;</code>
     * @return The employmentTypeId.
     */
    @java.lang.Override
    public int getEmploymentTypeId() {
      return employmentTypeId_;
    }
    /**
     * <code>int32 employment_type_id = 3;</code>
     * @param value The employmentTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentTypeId(int value) {
      
      employmentTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 employment_type_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmploymentTypeId() {
      
      employmentTypeId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object employmentType_ = "";
    /**
     * <code>string employment_type = 4;</code>
     * @return The employmentType.
     */
    public java.lang.String getEmploymentType() {
      java.lang.Object ref = employmentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employmentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employment_type = 4;</code>
     * @return The bytes for employmentType.
     */
    public com.google.protobuf.ByteString
        getEmploymentTypeBytes() {
      java.lang.Object ref = employmentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employmentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employment_type = 4;</code>
     * @param value The employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employmentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmploymentType() {
      
      employmentType_ = getDefaultInstance().getEmploymentType();
      onChanged();
      return this;
    }
    /**
     * <code>string employment_type = 4;</code>
     * @param value The bytes for employmentType to set.
     * @return This builder for chaining.
     */
    public Builder setEmploymentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employmentType_ = value;
      onChanged();
      return this;
    }

    private int careerLevelId_ ;
    /**
     * <code>int32 career_level_id = 5;</code>
     * @return The careerLevelId.
     */
    @java.lang.Override
    public int getCareerLevelId() {
      return careerLevelId_;
    }
    /**
     * <code>int32 career_level_id = 5;</code>
     * @param value The careerLevelId to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelId(int value) {
      
      careerLevelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 career_level_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevelId() {
      
      careerLevelId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object careerLevel_ = "";
    /**
     * <code>string career_level = 6;</code>
     * @return The careerLevel.
     */
    public java.lang.String getCareerLevel() {
      java.lang.Object ref = careerLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        careerLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string career_level = 6;</code>
     * @return The bytes for careerLevel.
     */
    public com.google.protobuf.ByteString
        getCareerLevelBytes() {
      java.lang.Object ref = careerLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        careerLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string career_level = 6;</code>
     * @param value The careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      careerLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevel() {
      
      careerLevel_ = getDefaultInstance().getCareerLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string career_level = 6;</code>
     * @param value The bytes for careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      careerLevel_ = value;
      onChanged();
      return this;
    }

    private int provinceId_ ;
    /**
     * <code>int32 province_id = 7;</code>
     * @return The provinceId.
     */
    @java.lang.Override
    public int getProvinceId() {
      return provinceId_;
    }
    /**
     * <code>int32 province_id = 7;</code>
     * @param value The provinceId to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceId(int value) {
      
      provinceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 province_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvinceId() {
      
      provinceId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <code>string province = 8;</code>
     * @return The province.
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string province = 8;</code>
     * @return The bytes for province.
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string province = 8;</code>
     * @param value The province to set.
     * @return This builder for chaining.
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string province = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>string province = 8;</code>
     * @param value The bytes for province to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private int publishStatusId_ ;
    /**
     * <code>int32 publish_status_id = 9;</code>
     * @return The publishStatusId.
     */
    @java.lang.Override
    public int getPublishStatusId() {
      return publishStatusId_;
    }
    /**
     * <code>int32 publish_status_id = 9;</code>
     * @param value The publishStatusId to set.
     * @return This builder for chaining.
     */
    public Builder setPublishStatusId(int value) {
      
      publishStatusId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 publish_status_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishStatusId() {
      
      publishStatusId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object publishStatus_ = "";
    /**
     * <code>string publish_status = 10;</code>
     * @return The publishStatus.
     */
    public java.lang.String getPublishStatus() {
      java.lang.Object ref = publishStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publishStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string publish_status = 10;</code>
     * @return The bytes for publishStatus.
     */
    public com.google.protobuf.ByteString
        getPublishStatusBytes() {
      java.lang.Object ref = publishStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publishStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string publish_status = 10;</code>
     * @param value The publishStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPublishStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publishStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string publish_status = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishStatus() {
      
      publishStatus_ = getDefaultInstance().getPublishStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string publish_status = 10;</code>
     * @param value The bytes for publishStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPublishStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      publishStatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string createdBy = 11;</code>
     * @return The createdBy.
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string createdBy = 11;</code>
     * @return The bytes for createdBy.
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdBy = 11;</code>
     * @param value The createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 11;</code>
     * @param value The bytes for createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.JobGrpc)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.JobGrpc)
  private static final com.wanpng.jobposting.grpc.domain.JobGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobposting.grpc.domain.JobGrpc();
  }

  public static com.wanpng.jobposting.grpc.domain.JobGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobGrpc>
      PARSER = new com.google.protobuf.AbstractParser<JobGrpc>() {
    @java.lang.Override
    public JobGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobposting.grpc.domain.JobGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

