// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/job.grpc.proto

package com.wanpng.jobposting.grpc.domain;

public interface JobGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string job_title = 2;</code>
   * @return The jobTitle.
   */
  java.lang.String getJobTitle();
  /**
   * <code>string job_title = 2;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();

  /**
   * <code>int32 employment_type_id = 3;</code>
   * @return The employmentTypeId.
   */
  int getEmploymentTypeId();

  /**
   * <code>string employment_type = 4;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 4;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <code>int32 career_level_id = 5;</code>
   * @return The careerLevelId.
   */
  int getCareerLevelId();

  /**
   * <code>string career_level = 6;</code>
   * @return The careerLevel.
   */
  java.lang.String getCareerLevel();
  /**
   * <code>string career_level = 6;</code>
   * @return The bytes for careerLevel.
   */
  com.google.protobuf.ByteString
      getCareerLevelBytes();

  /**
   * <code>int32 province_id = 7;</code>
   * @return The provinceId.
   */
  int getProvinceId();

  /**
   * <code>string province = 8;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 8;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>int32 publish_status_id = 9;</code>
   * @return The publishStatusId.
   */
  int getPublishStatusId();

  /**
   * <code>string publish_status = 10;</code>
   * @return The publishStatus.
   */
  java.lang.String getPublishStatus();
  /**
   * <code>string publish_status = 10;</code>
   * @return The bytes for publishStatus.
   */
  com.google.protobuf.ByteString
      getPublishStatusBytes();

  /**
   * <code>string createdBy = 11;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string createdBy = 11;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();
}
