// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/job.grpc.proto

package com.wanpng.jobposting.grpc.domain;

public final class JobGrpcProtos {
  private JobGrpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_JobGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_JobGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protos/domain/job.grpc.proto\022\rprotos.d" +
      "omain\"\371\001\n\007JobGrpc\022\n\n\002id\030\001 \001(\t\022\021\n\tjob_tit" +
      "le\030\002 \001(\t\022\032\n\022employment_type_id\030\003 \001(\005\022\027\n\017" +
      "employment_type\030\004 \001(\t\022\027\n\017career_level_id" +
      "\030\005 \001(\005\022\024\n\014career_level\030\006 \001(\t\022\023\n\013province" +
      "_id\030\007 \001(\005\022\020\n\010province\030\010 \001(\t\022\031\n\021publish_s" +
      "tatus_id\030\t \001(\005\022\026\n\016publish_status\030\n \001(\t\022\021" +
      "\n\tcreatedBy\030\013 \001(\tBd\n!com.wanpng.jobposti" +
      "ng.grpc.domainB\rJobGrpcProtosP\001Z.github." +
      "com/wanpng/job-posting-grpc/grpc/domainb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_JobGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_JobGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_JobGrpc_descriptor,
        new java.lang.String[] { "Id", "JobTitle", "EmploymentTypeId", "EmploymentType", "CareerLevelId", "CareerLevel", "ProvinceId", "Province", "PublishStatusId", "PublishStatus", "CreatedBy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
